import { Building } from "./buildings";
import { Item } from "./items";

export const production = {
  Fish: { fishingLodge: 1 },
  Cider: { ciderFarm: 1 },
  LinenGarments: { weaversHut: 1, hempPlantation: 2 },
  Spices: { spiceFarm: 1 },
  Bread: { bakery: 1, mill: 1, cropFarm: 2 },
  Beer: { monasteryBrewery: 1, cropFarm: 1, monasteryGarden: 1 },
  LeatherJerkins: {
    tannery: 1,
    pigFarm: 2,
    saltWorks: 0.5,
    saltMine: 0.5,
    charcoalBurnersHut: 0.5,
  },
  Books: { printingHouse: 1, indigoFarm: 2, paperMill: 0.5, lumberjacksHut: 1 },
  Candlesticks: {
    redsmithsWorkshop: 1,
    candlemakersWorkshop: 1.5,
    apiary: 3,
    hempPlantation: 1.5,
    copperSmelter: 0.75,
    copperMine: 0.75,
    charcoalBurnersHut: 0.5,
  },
  Meat: {
    butchery: 1,
    cattleFarm: 2,
    saltWorks: 0.48,
    saltMine: 0.48,
    charcoalBurnersHut: 0.48,
  },
  Wine: {
    winePress: 1,
    vineyard: 3,
    barrelCooperage: 1,
    lumberjacksHut: 0.665,
    ironSmelter: 0.5,
    ironMine: 0.5,
    charcoalBurnersHut: 0.5,
  },
  Glasses: {
    opticiansWorkshop: 1,
    quarzQuarry: 0.75,
    copperSmelter: 0.75,
    copperMine: 0.75,
    charcoalBurnersHut: 0.5,
  },
  FurCoats: {
    furriersWorkshop: 1,
    trappersLodge: 1,
    saltWorks: 19 / 60,
    saltMine: 19 / 60,
    charcoalBurnersHut: 19 / 60,
  },
  BrocadeRobes: {
    silkWeavingMill: 1,
    silkPlantation: 2,
    goldSmelter: 1,
    goldMine: 1,
    charcoalBurnersHut: 0.75,
  },
  Dates: { datePlantation: 1 },
  Milk: { goatFarm: 1 },
  Carpets: { carpetWorkshop: 1, silkPlantation: 1, indigoFarm: 1 },
  Coffee: { roastingHouse: 1, coffeePlantation: 2 },
  PearlNecklaces: { pearlWorkshop: 1, pearlFishersHut: 1 },
  Parfum: { perfumery: 1, roseNursery: 3 },
  Marzipan: {
    confectionersWorkshop: 1,
    almondPlantation: 2,
    sugarMill: 1,
    sugarCanePlantation: 2,
  },
} satisfies Record<Item, Partial<Record<Building, number>>>;
